module.exports = {
  attachment1: {
    aws_bucket: 'LGfuHdZgHXLddeKC',
    aws_content_length: 22757,
    aws_content_type: 'application/pdf',
    aws_etag: 'dcBsvxytnTvCdVXs',
    aws_key: 'dtEvdzgTMVEhSFer.pdf',
    name: 'Brunch skateboard polaroid, direct trade cold-pressed asymmetrical cloud bread shaman schlitz coloring book.',
  },
  attachment2: {
    aws_bucket: 'fdqHmmUPPrSWPUBN',
    aws_content_length: 30859,
    aws_content_type: 'application/pdf',
    aws_etag: 'xhWEhzWWPrZtcCZW',
    aws_key: 'nWVtrJqSrCxDwPqB.pdf',
    name: 'Organic man braid williamsburg tacos green juice fixie photo booth forage pok pok DIY hammock jianbing bushwick.',
  },
  attachment3: {
    aws_bucket: 'WchqmAEzqHWEEzpS',
    aws_content_length: 88505,
    aws_content_type: 'application/pdf',
    aws_etag: 'WdpEztmQDjkcAcVt',
    aws_key: 'DyERfLjXQMWuUcfS.pdf',
    name: 'Sustainable art party paleo beard pitchfork, PBR&B health goth glossier hella ennui pickled tbh.',
  },
  attachment4: {
    aws_bucket: 'wjAuHSPDaeNhMzUk',
    aws_content_length: 60975,
    aws_content_type: 'application/pdf',
    aws_etag: 'wnfBjzaZRafvNsZJ',
    aws_key: 'EJSmTtXgAhfWvaKG.pdf',
    name: 'Wolf copper mug artisan locavore, YOLO ugh iceland brunch mixtape echo park.',
  },
  attachment5: {
    aws_bucket: 'dYuvNuVdKKybznGU',
    aws_content_length: 13674,
    aws_content_type: 'application/pdf',
    aws_etag: 'YKCfNTQveeBwrNav',
    aws_key: 'hHcYThumNByGVGnA.pdf',
    name: 'Ethical pour-over hexagon four dollar toast, intelligentsia knausgaard sustainable.',
  },
  attachment6: {
    aws_bucket: 'UpMemAvzSGjNYbCM',
    aws_content_length: 43878,
    aws_content_type: 'application/pdf',
    aws_etag: 'ptLtAvDJHBAMvEeY',
    aws_key: 'drHaBmyzDuasbqgM.pdf',
    name: 'Synth hell of distillery, la croix tbh tousled dreamcatcher single-origin coffee.',
  },
  attachment7: {
    aws_bucket: 'dubGqgDAqXmHVwRY',
    aws_content_length: 57064,
    aws_content_type: 'application/pdf',
    aws_etag: 'FGuTgeFzDeBBkvmx',
    aws_key: 'jHVKnuXLKJusNafs.pdf',
    name: 'Direct trade twee squid, fanny pack 3 wolf moon vice typewriter vaporware ugh.',
  },
  attachment8: {
    aws_bucket: 'qNbPYXCTGMYGvxzF',
    aws_content_length: 958566,
    aws_content_type: 'application/pdf',
    aws_etag: 'ReMTHuRAcBQuJsrZ',
    aws_key: 'mwPcnErEwmKLVBNB.pdf',
    name: 'Pok pok kickstarter yuccie cliche, tofu banh mi yr schlitz street art. ',
  },
  attachment9: {
    aws_bucket: 'wYBHDCrFAXCGrkkZ',
    aws_content_length: 787117,
    aws_content_type: 'application/pdf',
    aws_etag: 'MkfuPpBJUpKqbMzV',
    aws_key: 'ZcrwxREaYCACsEaC.pdf',
    name: 'Shabby chic shaman typewriter organic hella pickled, chicharrones pug.',
  },
  attachment10: {
    aws_bucket: 'wrvVAhararjSRJyT',
    aws_content_length: 379285,
    aws_content_type: 'application/pdf',
    aws_etag: 'sbHJRXnmvpsghKMS',
    aws_key: 'ASYtXhMMptDYMbPU.pdf',
    name: 'Farm-to-table hashtag coloring book VHS health goth vinyl plaid swag.',
  },
  attachment11: {
    aws_bucket: 'tRqPkbCKmJaeAbJk',
    aws_content_length: 222361,
    aws_content_type: 'application/pdf',
    aws_etag: 'nrExkWpQYZRsZHYt',
    aws_key: 'HZSVBfsBwHqQREcp.pdf',
    name: 'Meditation retro man braid four dollar toast schlitz post-ironic.',
  },
  attachment12: {
    aws_bucket: 'dJtvqVcPXSJafBLQ',
    aws_content_length: 59103,
    aws_content_type: 'application/pdf',
    aws_etag: 'uXNybTkuaeEPLLVU',
    aws_key: 'TQeQGVxZCnQEFLhY.pdf',
    name: 'Snackwave sustainable edison bulb jianbing authentic sriracha.',
  },
  attachment13: {
    aws_bucket: 'XSHjfpGEzgYDvqKR',
    aws_content_length: 256275,
    aws_content_type: 'application/pdf',
    aws_etag: 'YqskquFLWqefHPdZ',
    aws_key: 'kkVQKhyFTCFAgBKa.pdf',
    name: 'Subway tile gluten-free narwhal, pour-over cardigan kale chips messenger bag health goth gochujang yuccie lomo truffaut organic. ',
  },
  attachment14: {
    aws_bucket: 'GPyWhYejjUcRScMX',
    aws_content_length: 522651,
    aws_content_type: 'application/pdf',
    aws_etag: 'duqKpnxuEKsGmLkw',
    aws_key: 'RqNNWnVzdtjdRZYq.pdf',
    name: 'Chicharrones edison bulb brooklyn, food truck dreamcatcher hoodie cronut tattooed pop-up man bun raclette air plant.',
  },
  attachment15: {
    aws_bucket: 'AfzgLMEGYuWCsDSH',
    aws_content_length: 422353,
    aws_content_type: 'application/pdf',
    aws_etag: 'bQTKkGzWGNTxDphb',
    aws_key: 'TMEjvYKyHpLvncPz.pdf',
    name: 'Godard VHS church-key artisan dreamcatcher post-ironic art party tattooed four loko affogato kinfolk heirloom humblebrag.',
  },
  attachment16: {
    aws_bucket: 'cqRRyzPytywWVwMf',
    aws_content_length: 827391,
    aws_content_type: 'application/pdf',
    aws_etag: 'fUZCTLPgZZYdgyep',
    aws_key: 'nMxfWLAFzrTPKVUP.pdf',
    name: 'Bitters cardigan PBR&B scenester meggings vexillologist, crucifix paleo.',
  },
  attachment17: {
    aws_bucket: 'jVmthhJRPpqwAcDA',
    aws_content_length: 338413,
    aws_content_type: 'application/pdf',
    aws_etag: 'PDcLRJYyJuJaGKAn',
    aws_key: 'jzshpcABeJnjbQde.pdf',
    name: 'Four loko mlkshk kickstarter shabby chic bushwick iPhone ugh kale chips flexitarian adaptogen photo booth bespoke semiotics.',
  },
  attachment18: {
    aws_bucket: 'FMYpcWDFnaMtNCXV',
    aws_content_length: 553826,
    aws_content_type: 'application/pdf',
    aws_etag: 'mKTkxykzpkdkvXfz',
    aws_key: 'FBnTNkNjrNFsRTaC.pdf',
    name: 'Cold-pressed chillwave retro jean shorts fashion axe, try-hard palo santo chia lyft mlkshk quinoa everyday carry.',
  },
  attachment19: {
    aws_bucket: 'eeWgEsBCxYHJRwve',
    aws_content_length: 429521,
    aws_content_type: 'application/pdf',
    aws_etag: 'ZfpAXMrvyNzXBUhw',
    aws_key: 'HuwPwjyEdmfPTEkP.pdf',
    name: 'Activated charcoal man braid salvia fanny pack +1 roof party cray hell of, venmo tumeric art party vape tofu.',
  },
  attachment20: {
    aws_bucket: 'UADZaFDsmAyzrXJS',
    aws_content_length: 974608,
    aws_content_type: 'application/pdf',
    aws_etag: 'LKQQeszPStuZZTLg',
    aws_key: 'sYPtwwKVWMWaYNnh.pdf',
    name: 'DIY pork belly normcore kale chips single-origin coffee flexitarian, pour-over tattooed helvetica distillery.',
  },
  attachment21: {
    aws_bucket: 'QUdwqjYWtJeKCAKP',
    aws_content_length: 584333,
    aws_content_type: 'application/pdf',
    aws_etag: 'aSeVXxSVbtKAvGsE',
    aws_key: 'NqpnGtFnhFURBWHP.pdf',
    name: 'Pork belly fixie vinyl 8-bit flexitarian synth try-hard, irony distillery lo-fi ennui shoreditch church-key seitan.',
  },
  attachment22: {
    aws_bucket: 'cvpLZGZNgcKvxqJa',
    aws_content_length: 425709,
    aws_content_type: 'application/pdf',
    aws_etag: 'MNyzVTLZpPKzLyXM',
    aws_key: 'xmgcdYGVEMzBzpfE.pdf',
    name: 'Bushwick chambray selfies direct trade vaporware craft beer meh +1 trust fund 3 wolf moon air plant humblebrag put a bird on it artisan.',
  },
  attachment23: {
    aws_bucket: 'qwzRHCHyryPeBnYJ',
    aws_content_length: 533408,
    aws_content_type: 'application/pdf',
    aws_etag: 'BWxKkbDGSNehdQDE',
    aws_key: 'JkxdtbAUhUFmDwnY.pdf',
    name: 'Mumblecore art party mustache, next level unicorn bitters coloring book enamel pin listicle fam shaman truffaut slow-carb.',
  },
  attachment24: {
    aws_bucket: 'SUJyhTyBPVUKMDNt',
    aws_content_length: 915323,
    aws_content_type: 'application/pdf',
    aws_etag: 'wtNGfYrNrxqrDFdk',
    aws_key: 'qkQTNYnzaykDfaTd.pdf',
    name: 'Knausgaard you probably haven\'t heard of them trust fund deep v, helvetica yr twee hell of green juice flexitarian ethical live-edge seitan yuccie.',
  },
  attachment25: {
    aws_bucket: 'JWWupmgqyCDcmMqC',
    aws_content_length: 565129,
    aws_content_type: 'application/pdf',
    aws_etag: 'rQyUxUcgxVRknPaj',
    aws_key: 'VNHZagWsMzqudZDt.pdf',
    name: 'IPhone vexillologist yuccie raw denim air plant cliche meditation kombucha whatever YOLO neutra fanny pack art party godard. ',
  },
  attachment26: {
    aws_bucket: 'xcZKTtbEMRsNTXzQ',
    aws_content_length: 105737,
    aws_content_type: 'application/pdf',
    aws_etag: 'vYbHRkGsnmuTsEjH',
    aws_key: 'SujBURpkChAvyxFa.pdf',
    name: 'Scenester direct trade aesthetic trust fund gluten-free intelligentsia leggings salvia polaroid artisan readymade.',
  },
  attachment27: {
    aws_bucket: 'HpkcjDQrbdPHLnMx',
    aws_content_length: 748325,
    aws_content_type: 'application/pdf',
    aws_etag: 'yadJQEAgGSGDUcmW',
    aws_key: 'MwJaLdVeTGuPVMyZ.pdf',
    name: 'Marfa mustache vinyl, aesthetic affogato before they sold out health goth chillwave stumptown ennui.',
  },
  attachment28: {
    aws_bucket: 'GLkFJDAVnfBjUTJp',
    aws_content_length: 554241,
    aws_content_type: 'application/pdf',
    aws_etag: 'uryHBrqBvkKYTJuN',
    aws_key: 'pVKNvtKdxWQFLUvQ.pdf',
    name: 'Hot chicken stumptown fanny pack marfa.',
  },
  attachment29: {
    aws_bucket: 'NYuddJjpFAuyJptr',
    aws_content_length: 719750,
    aws_content_type: 'application/pdf',
    aws_etag: 'xYvSTzEVLZBRNqeM',
    aws_key: 'QjdewYBhBkKCKuyw.pdf',
    name: 'Street art beard four dollar toast cred hot chicken tacos.',
  },
  attachment30: {
    aws_bucket: 'dcBsvxytnTvCdVXs',
    aws_content_length: 208608,
    aws_content_type: 'application/pdf',
    aws_etag: 'XHWhKdcjGwjWBTTX',
    aws_key: 'tzfNDXYVNUJfcDqj.pdf',
    name: 'Succulents you probably haven\'t heard of them vice portland, messenger bag yuccie sriracha sartorial 3 wolf moon mixtape.',
  },
};
