module.exports = {
  budget1: {
    amount_cents: 99763,
    month: 11,
    notes: 'Disrupt pickled before they sold out, direct trade lomo bicycle rights tacos actually beard sriracha raw denim.',
    year: 2018,
  },
  budget2: {
    amount_cents: 7114,
    month: 0,
    notes: 'Adaptogen pug raclette, blog normcore hexagon photo booth banjo farm-to-table intelligentsia.',
    year: 2010,
  },
  budget3: {
    amount_cents: 20839,
    month: 4,
    notes: 'Fixie lo-fi artisan single-origin coffee snackwave, offal cloud bread tilde poke blog post-ironic banh mi tumeric hella scenester.',
    year: 2001,
  },
  budget4: {
    amount_cents: 2926,
    month: 0,
    notes: 'Farm-to-table you probably haven\'t heard of them cornhole chicharrones snackwave palo santo schlitz cred, single-origin coffee williamsburg wayfarers flexitarian vaporware.',
    year: 2003,
  },
  budget5: {
    amount_cents: 28617,
    month: 3,
    notes: 'Intelligentsia air plant polaroid freegan plaid. Wolf typewriter copper mug helvetica iceland subway tile YOLO vexillologist.',
    year: 2015,
  },
  budget6: {
    amount_cents: 64671,
    month: 9,
    notes: 'Austin activated charcoal edison bulb, cred street art echo park scenester pop-up hammock pour-over direct trade enamel pin distillery YOLO taiyaki.',
    year: 2007,
  },
  budget7: {
    amount_cents: 21742,
    month: 10,
    notes: 'Four loko squid fam, farm-to-table brooklyn vinyl master cleanse locavore leggings viral.',
    year: 2014,
  },
  budget8: {
    budget: 225.02,
    amount_cents: 22502,
    month: 9,
    notes: 'Irony messenger bag XOXO gochujang glossier vegan lomo vaporware blue bottle.',
    year: 2009,
  },
  budget9: {
    amount_cents: 39746,
    month: 2,
    notes: 'Shabby chic bitters fam slow-carb before they sold out prism kickstarter stumptown occupy VHS direct trade vape waistcoat kitsch shoreditch.',
    year: 2003,
  },
  budget10: {
    amount_cents: 75993,
    month: 4,
    notes: 'Squid copper mug next level, seitan cardigan air plant occupy banjo listicle vegan freegan palo santo tbh.',
    year: 2016,
  },
  budget11: {
    amount_cents: 14156,
    month: 5,
    notes: 'Activated charcoal actually hexagon marfa, normcore hoodie XOXO enamel pin jianbing williamsburg.',
    year: 2017,
  },
  budget12: {
    amount_cents: 43294,
    month: 9,
    notes: 'Portland next level hammock yr occupy crucifix street art wolf, meditation kitsch la croix freegan poke godard pickled.',
    year: 2000,
  },
  budget13: {
    amount_cents: 90756,
    month: 1,
    notes: 'Fam edison bulb vice you probably haven\'t heard of them intelligentsia tattooed farm-to-table affogato air plant squid umami pitchfork.',
    year: 2006,
  },
  budget14: {
    amount_cents: 85985,
    month: 5,
    notes: 'Marfa before they sold out YOLO, raclette enamel pin literally kitsch yuccie.',
    year: 2007,
  },
  budget15: {
    amount_cents: 20064,
    month: 2,
    notes: 'Biodiesel pour-over palo santo, chambray iceland slow-carb snackwave.',
    year: 2019,
  },
  budget16: {
    amount_cents: 88233,
    month: 10,
    notes: '+1 prism flexitarian PBR&B portland iceland try-hard, squid truffaut food truck master cleanse.',
    year: 2009,
  },
  budget17: {
    amount_cents: 78861,
    month: 6,
    notes: 'Fixie chambray air plant offal tofu portland succulents bicycle rights jianbing.',
    year: 2010,
  },
  budget18: {
    amount_cents: 2173,
    month: 5,
    notes: 'Narwhal cray live-edge offal cloud bread.',
    year: 2000,
  },
  budget19: {
    amount_cents: 97952,
    month: 10,
    notes: 'Brooklyn salvia fixie asymmetrical.',
    year: 2010,
  },
  budget20: {
    amount_cents: 59887,
    month: 3,
    notes: 'Helvetica tumeric four dollar toast umami authentic subway tile selfies shoreditch cronut fashion axe slow-carb marfa celiac.',
    year: 2004,
  },
  budget21: {
    amount_cents: 5702,
    month: 11,
    notes: 'Post-ironic pour-over gentrify artisan, sustainable typewriter chia mustache.',
    year: 2006,
  },
  budget22: {
    amount_cents: 76914,
    month: 8,
    notes: 'Leggings fanny pack chambray neutra.',
    year: 2020,
  },
  budget23: {
    amount_cents: 61537,
    month: 10,
    notes: 'Taiyaki synth cronut everyday carry art party stumptown tbh meh.',
    year: 2012,
  },
  budget24: {
    amount_cents: 84823,
    month: 3,
    notes: 'Small batch yuccie air plant pitchfork mlkshk.',
    year: 2018,
  },
  budget25: {
    amount_cents: 87042,
    month: 2,
    notes: 'Small batch jianbing glossier cray, chicharrones literally sriracha tousled unicorn iPhone semiotics.',
    year: 2013,
  },
  budget26: {
    amount_cents: 97038,
    month: 11,
    notes: 'Portland stumptown XOXO pour-over, street art kale chips la croix meditation ethical wolf jianbing.',
    year: 2017,
  },
  budget27: {
    amount_cents: 71135,
    month: 1,
    notes: 'Hell of four loko hoodie adaptogen shoreditch keffiyeh thundercats etsy locavore coloring book tote bag normcore vegan.',
    year: 2014,
  },
  budget28: {
    amount_cents: 9952,
    month: 6,
    notes: 'Freegan literally kinfolk flannel selvage try-hard.',
    year: 2012,
  },
  budget29: {
    amount_cents: 42462,
    month: 2,
    notes: 'Chia freegan four loko etsy, locavore readymade seitan vice cardigan typewriter vaporware lyft.',
    year: 2000,
  },
  budget30: {
    amount_cents: 94284,
    month: 0,
    notes: 'Lo-fi brunch try-hard typewriter fanny pack crucifix cray chicharrones kitsch fam farm-to-table sartorial edison bulb literally.',
    year: 2002,
  },
};
